# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
# See: https://nikitabobko.github.io/AeroSpace/goodness#open-a-new-window-with-applescript
alt-enter = '''exec-and-forget osascript -e '
tell application "Terminal"
    do script
    activate
end tell'
'''

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-l = 'focus-back-and-forth'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
cmd-ctrl-alt-shift-equal = 'move left'
cmd-ctrl-alt-shift-minus = 'move right'
cmd-ctrl-alt-shift-leftSquareBracket = 'workspace prev'
cmd-ctrl-alt-shift-rightSquareBracket = 'workspace next'

cmd-ctrl-alt-shift-tab = 'workspace-back-and-forth'
cmd-ctrl-alt-shift-quote = 'focus right'
cmd-ctrl-alt-shift-semicolon = 'focus left'

alt-s = 'layout v_accordion' # 'layout stacking' in i3
alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

cmd-ctrl-alt-shift-1 = 'workspace 1'
cmd-ctrl-alt-shift-2 = 'workspace 2'
cmd-ctrl-alt-shift-3 = 'workspace 3'
cmd-ctrl-alt-shift-4 = 'workspace 4'
cmd-ctrl-alt-shift-5 = 'workspace 5'
cmd-ctrl-alt-shift-6 = 'workspace 6'
cmd-ctrl-alt-shift-7 = 'workspace 7'
cmd-ctrl-alt-shift-8 = 'workspace 8'
cmd-ctrl-alt-shift-9 = 'workspace 9'
cmd-ctrl-alt-shift-0 = 'workspace 10'

ctrl-shift-1 = 'move-node-to-workspace 1'
ctrl-shift-2 = 'move-node-to-workspace 2'
ctrl-shift-3 = 'move-node-to-workspace 3'
ctrl-shift-4 = 'move-node-to-workspace 4'
ctrl-shift-5 = 'move-node-to-workspace 5'
ctrl-shift-6 = 'move-node-to-workspace 6'
ctrl-shift-7 = 'move-node-to-workspace 7'
ctrl-shift-8 = 'move-node-to-workspace 8'
ctrl-shift-9 = 'move-node-to-workspace 9'
ctrl-shift-0 = 'move-node-to-workspace 10'

alt-shift-c = 'reload-config'
cmd-ctrl-alt-shift-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'


# Desktop

# [[on-window-detected]]
# if.app-id = 'com.github.wez.wezterm'  # WezTerm
# run = 'move-node-to-workspace 1'       # Terminal workspace

# [[on-window-detected]]
# if.app-id = 'org.mozilla.firefox'      # Firefox
# run = 'move-node-to-workspace 1'       # Browser workspace

# [[on-window-detected]]
# if.app-id = 'com.figma.Desktop'        # Figma
# run = 'move-node-to-workspace 2'       # Design workspace

# [[on-window-detected]]
# if.app-id = "net.whatsapp.WhatsApp"
# run = 'move-node-to-workspace 3'       # Communication workspace

# [[on-window-detected]]
# if.app-id = 'com.cron.electron'        # Calendar
# run = 'move-node-to-workspace 4'       

# [[on-window-detected]]
# if.app-id = 'com.spotify.client'        # Spotify
# run = 'move-node-to-workspace 5'       # Design workspace

# Laptop

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'  # WezTerm
run = 'move-node-to-workspace 1'       # Terminal workspace

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'      # Firefox
run = 'move-node-to-workspace 2'       # Browser workspace

[[on-window-detected]]
if.app-id = 'com.figma.Desktop'        # Figma
run = 'move-node-to-workspace 3'       # Design workspace

[[on-window-detected]]
if.app-id = "net.whatsapp.WhatsApp"
run = 'move-node-to-workspace 4'       # Communication workspace

[[on-window-detected]]
if.app-id = 'com.cron.electron'        # Calendar
run = 'move-node-to-workspace 5'       

[[on-window-detected]]
if.app-id = 'com.spotify.client'        # Spotify
run = 'move-node-to-workspace 6'       # Design workspace

[gaps]
inner.horizontal = 40
inner.vertical =   40
outer.left =       40
outer.bottom =     40
outer.top =        40
outer.right =      40
