theme = "jellybeans-custom"

[editor]
idle-timeout = 0
line-number = "relative"
mouse = false
true-color = true
color-modes = true
scrolloff = 25

[editor.lsp]
display-inlay-hints = false
display-messages = true
auto-signature-help = false
snippets = true

[editor.file-picker]
hidden = false
git-ignore = true

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "file-name", "diagnostics"]
right = ["version-control", "selections", "position", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# [editor.inline-diagnostics]
# cursor-line = "hint"
# other-lines = "error"

[editor.search]
smart-case = true

[editor.soft-wrap]
enable = true

[keys.normal]
C-space = "goto_last_accessed_file" # Maps the Ctrl-s to the typable command :w which is an alias for :write (save file)
C-d = ["half_page_down", "goto_window_center"]
C-u = ["half_page_up", "goto_window_center"]
C-r = ":reload"
n = ["search_next", "align_view_center"]
N = ["search_prev", "align_view_center"]
V = ["goto_first_nonwhitespace", "extend_to_line_end"]
D = ["ensure_selections_forward", "extend_to_line_end"]
H = ["select_mode", "goto_line_start", "normal_mode"]
L = ["select_mode", "goto_line_end", "normal_mode"]
K = "extend_next_word_end"
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_above"
x = "extend_line_below"
ret = "collapse_selection"
G = "goto_file_end"
C-t = "jump_backward"
C-y = "jump_forward"


[keys.select]
";" = ["collapse_selection", "normal_mode"]
x = "extend_line"
V = "extend_to_line_end"

[keys.normal.space]
w = ":write"
q = ":buffer-close"
space = "goto_last_accessed_file" 
i = "goto_word"
z = ":yank-diagnostic"
