[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "tailwindcss-ls" ]
auto-format = true
formatter = { command = "biome", args = ["format", "--stdin-file-path", "file.js"] }

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "tailwindcss-ls" ]
auto-format = true
formatter = { command = "biome", args = ["format", "--stdin-file-path", "file.ts"] }

[[language]]
name = "tsx"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "tailwindcss-ls"]
auto-format = true
formatter = { command = "biome", args = ["format", "--stdin-file-path", "file.tsx"] }

[[language]]
name = "jsx"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome", "tailwindcss-ls"]
auto-format = true
formatter = { command = "biome", args = ["format", "--stdin-file-path", "file.jsx"] }

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true
formatter = { command = "biome", args = ["format", "--stdin-file-path", "file.json"] }

[[language]]
name = "markdown"
auto-format = true
language-servers = [ "markdown-oxide" ]
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}

[[language]]
name = "html"
language-servers = [{ name = "superhtml", except-features = ["format"] }, "vscode-html-language-server"]
auto-format = true

[[language]]
name = "php"
auto-format = true
formatter = { command = "php-cs-fixer", args = ["fix", "--using-cache=no", "-"] }
