color = ''
project-name = 'default'
[default]
account_id = 'acct_1QMCLy05BCWHhnEg'
device_name = 'cemals-air.local'
display_name = 'Bobbe'
live_mode_api_key = 'rk_live_***********************************************************************************************x9Nh'
live_mode_key_expires_at = '2025-05-31'
live_mode_pub_key = 'pk_live_51QMCLy05BCWHhnEgTfVQulVVtuNV94Sx0Wskfm1ME0AH1X8VBEFAqG2aHitKTlDeG9TBIgZpPbBlMAEykI0xLoLW00V1NxDazV'
test_mode_api_key = 'rk_test_51QMCLy05BCWHhnEgnrFmIFNKDF2P9uFqwbeQ0gPPOchpWghNvI4eMumJ5ISsi58XSIRnvia3N6dCVJvIUN5OCx8300LGT4lYBq'
test_mode_key_expires_at = '2025-05-31'
test_mode_pub_key = 'pk_test_51QMCLy05BCWHhnEgbYlcTc9TfLwFDojmFzu14kOIherMEoJEVhw92BJRWKeWlWn6YbTxlBAQGeIjuTMD33FcVtBQ00oOxVyXx1'

